export const taskList = [
  {
    id: 41,
    title: "po",
    content: "po",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T20:44:56.479544Z",
    workers: [1, 3],
  },
  {
    id: 40,
    title: "p",
    content: "p",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T20:39:54.968977Z",
    workers: [2],
  },
  {
    id: 39,
    title: "p",
    content: "p",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T20:39:53.277151Z",
    workers: [2],
  },
  {
    id: 38,
    title: "bebebe",
    content: "bobobo",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T20:36:03.449935Z",
    workers: [1, 2],
  },
  {
    id: 37,
    title: "bababa",
    content: "vovovo",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T20:31:38.474543Z",
    workers: [1, 2],
  },
  {
    id: 36,
    title: "да бля",
    content: "бля",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T13:54:05.244962Z",
    workers: [1],
  },
  {
    id: 35,
    title: "довари рис",
    content: "рис рисочек",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-25T13:52:50.425356Z",
    workers: [1],
  },
  {
    id: 34,
    title: "Вынестить мусор",
    content: "Вынести металлолом из помещения",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-24T22:31:50.846436Z",
    workers: [1, 11, 12, 13],
  },
  {
    id: 33,
    title: "kjh",
    content: "lkjlkj",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-24T21:48:09.362723Z",
    workers: [1, 2],
  },
  {
    id: 32,
    title: "boba",
    content: "aboba",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-24T21:47:31.233847Z",
    workers: [1, 2],
  },
  {
    id: 31,
    title: "Собрать клетку",
    content: "Изготовить новую клетку из чего-нибудь.",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-24T21:35:44.019007Z",
    workers: [1, 2, 3],
  },
  {
    id: 29,
    title: "Починить ворота",
    content: "Заменить ламель ворота в-6",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-11-24T21:33:14.327835Z",
    workers: [1],
  },
  {
    id: 2,
    title: "Drink some beer",
    content: "Get drunk after work and go to the moon",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-10-30T09:43:24.857345Z",
    workers: [1, 2],
  },
  {
    id: 1,
    title: "Починить лифт",
    content: "Надо поставить таль на место",
    workgroup_id: 1,
    workgroup_name: "СГИ Ф-3",
    created_at: "2023-10-19T22:35:37.298360Z",
    workers: [2],
  },
  {
    id: 30,
    title: "Заменить аккумулятор",
    content: "Аккумулятор погрузчика",
    workgroup_id: 6,
    workgroup_name: "Электромеханики",
    created_at: "2023-11-24T21:33:59.664556Z",
    workers: [9, 10],
  },
];

export const workgroups = [
  {
    id: 1,
    name: "СГИ Ф-3",
    workers: [
      {
        id: 1,
        first_name: "",
        last_name: "",
        username: "nikki",
      },
      {
        id: 2,
        first_name: "Антон",
        last_name: "Денисов",
        username: "denisov",
      },
      {
        id: 3,
        first_name: "коленька",
        last_name: "рюрюсик",
        username: "kokosik",
      },
      {
        id: 11,
        first_name: "Петрович",
        last_name: "",
        username: "petrovich",
      },
      {
        id: 12,
        first_name: "Павел",
        last_name: "",
        username: "Pavel",
      },
      {
        id: 13,
        first_name: "",
        last_name: "",
        username: "volodya",
      },
    ],
  },
  {
    id: 6,
    name: "Электромеханики",
    workers: [
      {
        id: 9,
        first_name: "Василий",
        last_name: "",
        username: "vasiliy",
      },
      {
        id: 10,
        first_name: "Алексей",
        last_name: "",
        username: "alexey",
      },
    ],
  },
];

export const mockUser = {
  id: 2,
  username: "denisov",
  first_name: "Антон",
  last_name: "Денисов",
  is_master: true,
};
